apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replica-controller
  labels:
    label1: test

spec:
  template: 
    metadata: 
      name: container1
      labels:
        label1: test123
    spec:
      containers:
        - name: nginx-test
          image: nginx
  replicas: 3