apiVersion: v1      #Required
kind: Pod           #Required
metadata:           #Required
  name: myapp
  labels:
    name: myapp
    testlabel: mytest1   #Custom Label
spec:                     #Required
  securityContext:
    runAsUser: 1000
  serviceAccount: myaccount1
  automountServiceAccountToken: false
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "PreferNoSchedule"
  nodeSelector:
    size: large
  containers:
  - name: myapp-frontend
    image: nginx
    securityContext:
      capabilities:
        add: ["MAC_ADMIN"]
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "200m"
    ports:
    - containerPort: 80
    command:
      - sleep
    args:
      - "3600"
    env:
      - name: var1
        value: data1
  - name: myapp-backend
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

    
