apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flighttickets.flights.com
spec:
  group: flights.com     # group name to use for REST API: /apis/<group>/<version>
  scope: Namespaced      # either Namespaced or Cluster
  names:
    plural: flighttickets   # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    singular: flightticket  # singular name to be used as an alias on the CLI and for display
    kind: FlighTicket       # kind is normally the CamelCased singular type. Your resource manifests use this.
    shortNames:             # shortNames allow shorter string to match your resource on the CLI
    - ft      
  versions:
    - name: v1
      served: true
      storage: true            # One and only one version must be marked as the storage version.
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                from:       
                  type: string
                to:
                  type: string
                number:
                  type: integer
                  minimum: 1
                  maximum: 10
---
apiVersion: flights.com/v1
kind: FlighTicket
metadata:
  name: ticket1
spec:
  from: london
  to: dubai
  number: 5