apiVersion: v1
kind: Secret
metadata:
  name: secret1
data:
  username: dGVzdA==  #echo -n "test" | base64
  password: dGVzdDI=  #echo -n "test2" | base64

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-test-app
  labels:
    name: secret-test-app
spec:
  containers:
  - name: secret-test-app
    env:
    - name: test
      valueFrom:
        secretKeyRef:
          name: secret1
          key: password
    envFrom:
    - secretRef:
        name: secret1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
