apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon-test
  namespace: default
  labels:
    k8s-app: nginx-daemon
spec:
  selector:
    matchLabels:
      name: nginx-daemon
  template:
    metadata:
      labels:
        name: nginx-daemon
    spec:
      containers:
      - name: nginx-daemon
        image: nginx