apiVersion: v1
kind: Pod
metadata:
  name: pod-custom
  labels:
    name: pod-custom
spec:
  containers:
  - name: pod-custom
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  schedulerName: my-scheduler
